In [1]:
import numpy as np
import pandas as pd

In [15]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [9]:
X_train

age  gender  fever   cough       city
59    6  Female  104.0    Mild    Kolkata
21   73    Male   98.0    Mild  Bangalore
54   60  Female   99.0    Mild     Mumbai
30   15    Male  101.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
..  ...     ...    ...     ...        ...
53   83    Male   98.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore
9    64  Female  101.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
2    42    Male  101.0    Mild      Delhi

[80 rows x 5 columns]

# 1. Aam Zindagi

In [13]:
# fill in the missing values in fever
si = SimpleImputer(strategy="mean")
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [17]:
# Ordinalencoding in cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
oe

OrdinalEncoder(categories=[['Mild', 'Strong']])

In [20]:
X_train_oe = oe.fit_transform(X_train[['cough']])
X_tst_oe = oe.transform(X_test[['cough']])

In [22]:
X_train_oe.shape

(80, 1)

In [26]:
# OneHotEncoding in gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_ohe = ohe.fit_transform(X_train[['gender','city']])
X_test_ohe = ohe.transform(X_test[['gender','city']])

In [27]:
X_train_ohe.shape

(80, 4)

In [28]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape


(80, 1)

In [31]:
X_train_transformed = np.concatenate((X_train_age,X_train_ohe,X_train_oe,X_train_fever),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_ohe,X_tst_oe,X_test_fever),axis=1)

X_train_transformed

array([[  6.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        , 104.        ],
       [ 73.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  98.        ],
       [ 60.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  99.        ],
       [ 15.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        , 101.        ],
       [ 75.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        , 100.79452055],
       [ 12.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  98.        ],
       [ 38.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        , 100.79452055],
       [ 25.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  99.        ],
       [ 51.        ,   0.        ,   0.        ,   1.        ,
          0.    

# Mentos Zindagi

In [32]:
from sklearn.compose import ColumnTransformer

In [44]:
df = pd.read_csv('covid_toy.csv')
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [48]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [49]:
transformer.fit_transform(X_train)

array([[100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  60.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [50]:
transformer.transform(X_test)

array([[100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ],
       [101.04225352,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    